apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp2-deployment
spec:
  selector:
    matchLabels:
      app: testapp2
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: testapp2 
        image: 192.168.1.50:5000/testapp2:v0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8082

      imagePullSecrets:
      - name: regcred
