apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgo-deployment
spec:
  selector:
    matchLabels:
      app: testgo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: testgo
    spec:
      containers:
      - name: testgo
        # image: docker.io/library/testgo:v0.1
        image: 192.168.1.50:5000/testgo:v0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080

      imagePullSecrets:
      - name: regcred
