// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Curl(arg1) {
  return window['go']['main']['App']['Curl'](arg1);
}

export function GetTpl(arg1) {
  return window['go']['main']['App']['GetTpl'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Save(arg1, arg2, arg3) {
  return window['go']['main']['App']['Save'](arg1, arg2, arg3);
}
