// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Curl(arg1:string):Promise<string>;

export function GetFile(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Paste():Promise<string>;

export function Save(arg1:string,arg2:string,arg3:string):Promise<void>;
